# Set our base image
FROM serversideup/php:8.2-fpm-nginx-v2.2.1

# Install PHP Imagemagick using regular Ubuntu commands
RUN apt-get update \
    && apt-get install -y --no-install-recommends php8.0-imagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*


COPY . /var/www/html

# Build the application
RUN composer install --no-dev --no-interaction --optimize-autoloader --no-progress --no-suggest --no-scripts


